### ISSUE TITLE
Question-answer-comment relationship & votes implementation

### ISSUE THREAD

**Issue by ddanielgal** [DevTeamSCH/vikoverflow#15]
Mattermost:

> Egy comment-ben vagy answer-ben melyik field adja meg a parent question-t vagy answert?
> A parent field egy Votes-ra mutat, ami a szavazatokat tárolja
> A Votes-ban pedig profilok vannak.
> Nem lenne úgy jobb, hogy a Answer-nek a parent egy Question, a Comment-nek pedig AbstractComment? a Votes pedig mehet az AbstractComment-be OneToOneField-nek, mert mindhárom "komment típusra" lehet szavazni

**Comment by barni2000** [comment]
Vote just aggregates the votes for the question, anwser and comment.
Question, Anwser, Comment are flat thay dont have real parents.

**Comment by ddanielgal** [comment]
Then how do I get the answers to a question, comments to an answer, ... ? I think there needs to be a parent-child relationship between these things.

**Comment by ddanielgal** [comment]
Q-A-C model restructure: https://github.com/DevTeamSCH/vikoverflow-backend/pull/11
Voting: https://github.com/DevTeamSCH/vikoverflow-backend/pull/12
