### ISSUE TITLE
Fixtures

### ISSUE THREAD

**Issue by ddanielgal** [DevTeamSCH/vikoverflow#8]
Sample data.
https://docs.djangoproject.com/en/2.1/howto/initial-data/

- [x] Users
- [x] Profiles
- [x] Questions
- [ ] Answers
- [ ] Comments
- [ ] Tags
- [ ] Courses
- [ ] Reports
- [ ] ModeratorComments

**Comment by danielgaldev** [comment]
- [ ] Users
- [ ] Profiles
- [ ] Questions
- [ ] Answers
- [ ] Comments
- [ ] Tags
- [ ] Courses
- [ ] Reports
- [ ] ModeratorComments

**Comment by ddanielgal** [comment]
Replaced with `populate.py` script.
